name: Release
on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
    Release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v4
            - name: Setup Java JDK
              uses: actions/setup-java@v4
              with:
                distribution: 'oracle'
                java-version: 17                    
                cache: maven
            - name: Create Package.zip with JARs
              run: |
                mvn --batch-mode --update-snapshots verify
                mkdir staging && cp target/*.jar staging
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                files: |
                    target/*.jar
                    LICENSE
